serveur:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/democinema?allowPublicKeyRetrieval=true&userSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
